;;; jump-char-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from jump-char.el

(autoload 'jump-char-forward "jump-char" "\
Prompt for a character, and jump to the next occurrence of that character.
Invokes `ace-jump-line-mode' when called with prefix.

When jump-char is active:

| key     | does                                                                           |
|---------+--------------------------------------------------------------------------------|
| <char>  | move to the next match in the current direction.                               |
| ;       | next match forward (towards end of buffer) see `jump-char-forward-key'         |
| ,       | next match backward (towards beginning of buffer) see `jump-char-backward-key' |
| C-c C-c | invoke `ace-jump-mode' if available                                            |

Any other key stops jump-char and edits as normal.

(fn ARG)" t)
(autoload 'jump-char-backward "jump-char" "\
backward movement version of `jump-char-forward'

(fn ARG)" t)
(autoload 'jump-char-forward-set-mark "jump-char" "\
See `jump-char-forward', set-mark if not active.

(fn ARG)" t)
(autoload 'jump-char-backward-set-mark "jump-char" "\
See `jump-char-backward', set-mark if not active.

(fn ARG)" t)
(register-definition-prefixes "jump-char" '("jump-char-"))

;;; End of scraped data

(provide 'jump-char-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; jump-char-autoloads.el ends here
